services:
  hello-java-server:
    build: .
    container_name: java-grpc-java-server
    networks:
      - grpcnet

  hello-java-client:
    build: .
    container_name: java-grpc-java-client
    networks:
      - grpcnet
    depends_on:
      - hello-java-server

networks:
  grpcnet:
    name: grpcnet
    driver: bridge
